'use client'

/**
 * Verifiability report panel for the blog edit page. Shows the most recent
 * AI fact-check result with a per-claim breakdown, a Re-verify button, and
 * a per-claim "Fix in article" action that previews + applies a correction
 * generated by Claude.
 *
 * Only renders for AI-generated posts. Manual posts don't get a score.
 */

import { useState } from 'react'

interface Claim {
  claim: string
  status: 'verified' | 'unverified' | 'false'
  source?: string | null
  reasoning?: string | null
}

interface Report {
  score: number
  total_claims: number
  verified: number
  unverified: number
  false_count: number
  summary: string
  claims: Claim[]
  ran_at: string
  model: string
}

interface Props {
  postId: number
  aiGenerated: boolean
  score: number | null
  checkedAt: string | null
  report: Report | null
  visibility: string
}

interface FixPreview {
  claimIndex: number
  claim: Claim
  original_text: string
  corrected_text: string
  explanation: string
  found: boolean
}

export function VerifiabilityPanel({
  postId, aiGenerated, score, checkedAt, report, visibility,
}: Props) {
  const [verifying, setVerifying] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [latestReport, setLatestReport] = useState<Report | null>(report)
  const [latestScore, setLatestScore] = useState<number | null>(score)
  const [latestCheckedAt, setLatestCheckedAt] = useState<string | null>(checkedAt)
  const [latestTrashed, setLatestTrashed] = useState<boolean>(false)
  const [expanded, setExpanded] = useState(false)

  // Per-claim fix state
  const [fixingIndex, setFixingIndex] = useState<number | null>(null)
  const [fixError, setFixError] = useState<string | null>(null)
  const [fixPreview, setFixPreview] = useState<FixPreview | null>(null)
  const [applying, setApplying] = useState(false)
  const [appliedIndices, setAppliedIndices] = useState<Set<number>>(new Set())

  if (!aiGenerated) return null

  async function runVerify() {
    if (!confirm('Run the AI fact-checker on this post? It uses web search and takes ~10-20 seconds. If the score comes back below the threshold, this post will be moved to trash.')) return
    setVerifying(true)
    setError(null)
    try {
      const res = await fetch(`/api/admin/blog/${postId}/verify`, { method: 'POST' })
      const data = await res.json()
      if (!res.ok || !data.ok) throw new Error(data.error || 'Verification failed')
      setLatestReport(data.report)
      setLatestScore(data.score)
      setLatestCheckedAt(data.report?.ran_at ?? new Date().toISOString())
      setLatestTrashed(!!data.trashed)
      setExpanded(true)
      setAppliedIndices(new Set())
      // If trashed, refresh page after a moment so the status bar updates
      if (data.trashed) {
        setTimeout(() => window.location.reload(), 2000)
      }
    } catch (e: any) {
      setError(e.message)
    } finally {
      setVerifying(false)
    }
  }

  async function previewFix(claim: Claim, index: number) {
    setFixingIndex(index)
    setFixError(null)
    setFixPreview(null)
    try {
      const res = await fetch(`/api/admin/blog/${postId}/fix-claim`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'preview',
          claim: claim.claim,
          status: claim.status,
          source: claim.source,
          reasoning: claim.reasoning,
        }),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) throw new Error(data.error || 'Could not generate fix')
      setFixPreview({
        claimIndex: index,
        claim,
        original_text: data.original_text,
        corrected_text: data.corrected_text,
        explanation: data.explanation || '',
        found: !!data.found,
      })
    } catch (e: any) {
      setFixError(e.message)
    } finally {
      setFixingIndex(null)
    }
  }

  async function applyFix() {
    if (!fixPreview) return
    setApplying(true)
    setFixError(null)
    try {
      const res = await fetch(`/api/admin/blog/${postId}/fix-claim`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          mode: 'apply',
          original_text: fixPreview.original_text,
          corrected_text: fixPreview.corrected_text,
        }),
      })
      const data = await res.json()
      if (!res.ok || !data.ok) throw new Error(data.error || 'Failed to apply fix')
      const idx = fixPreview.claimIndex
      setAppliedIndices(prev => {
        const next = new Set(prev)
        next.add(idx)
        return next
      })
      setFixPreview(null)
      // Reload so the editor below picks up the new content
      setTimeout(() => window.location.reload(), 400)
    } catch (e: any) {
      setFixError(e.message)
    } finally {
      setApplying(false)
    }
  }

  function closeModal() {
    if (applying) return
    setFixPreview(null)
    setFixError(null)
  }

  // Color the score badge
  let badgeCls = 'bg-gray-100 text-gray-600'
  if (latestScore != null) {
    if (latestScore >= 85) badgeCls = 'bg-green-100 text-green-700'
    else if (latestScore >= 60) badgeCls = 'bg-yellow-100 text-yellow-700'
    else badgeCls = 'bg-red-100 text-red-700'
  }

  return (
    <div className="admin-card mb-6">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3">
          <div>
            <h3 className="text-sm font-semibold text-gray-900">AI Verifiability Report</h3>
            <p className="text-xs text-gray-500">
              {latestCheckedAt
                ? `Last checked ${new Date(latestCheckedAt).toLocaleString('en-US', { timeZone: 'America/Los_Angeles', month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })} PT`
                : 'AI-generated — has not been fact-checked yet'}
            </p>
          </div>
          {latestScore != null && (
            <span className={`inline-flex items-center px-3 py-1 text-sm font-bold rounded-full ${badgeCls}`}>
              {latestScore}/100
            </span>
          )}
          {latestTrashed && (
            <span className="text-xs font-semibold text-red-700 bg-red-50 border border-red-200 rounded px-2 py-1">
              Auto-discarded — moved to trash
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          {latestReport && (
            <button type="button" onClick={() => setExpanded(e => !e)}
              className="text-xs text-gray-500 hover:text-gray-700">
              {expanded ? 'Hide details' : 'Show details'}
            </button>
          )}
          <button type="button" onClick={runVerify} disabled={verifying}
            className="btn-outline text-xs disabled:opacity-50">
            {verifying ? (
              <span className="flex items-center gap-1.5">
                <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Verifying…
              </span>
            ) : (latestScore != null ? 'Re-verify' : 'Run verification')}
          </button>
        </div>
      </div>

      {error && (
        <p className="mt-2 text-xs text-red-600">{error}</p>
      )}

      {latestReport && expanded && (
        <div className="mt-4 pt-4 border-t border-gray-100 space-y-3">
          {/* Stats */}
          <div className="flex items-center gap-4 text-xs">
            <div><span className="text-gray-400">Total claims:</span> <span className="font-semibold text-gray-700">{latestReport.total_claims}</span></div>
            <div><span className="text-green-700 font-semibold">{latestReport.verified}</span> verified</div>
            <div><span className="text-yellow-700 font-semibold">{latestReport.unverified}</span> unverified</div>
            <div><span className="text-red-700 font-semibold">{latestReport.false_count}</span> false</div>
          </div>

          {latestReport.summary && (
            <p className="text-xs text-gray-600 italic bg-gray-50 rounded p-2 border border-gray-100">
              {latestReport.summary}
            </p>
          )}

          {/* Claims list */}
          {latestReport.claims.length > 0 && (
            <div className="space-y-1.5">
              {latestReport.claims.map((c, i) => {
                const tone = c.status === 'verified' ? 'border-green-200 bg-green-50'
                  : c.status === 'false' ? 'border-red-200 bg-red-50'
                  : 'border-yellow-200 bg-yellow-50'
                const dot = c.status === 'verified' ? 'bg-green-500'
                  : c.status === 'false' ? 'bg-red-500'
                  : 'bg-yellow-500'
                const fixable = c.status === 'false' || c.status === 'unverified'
                const isFixing = fixingIndex === i
                const wasApplied = appliedIndices.has(i)
                return (
                  <div key={i} className={`text-xs border rounded p-2 ${tone}`}>
                    <div className="flex items-start gap-2">
                      <span className={`w-2 h-2 rounded-full mt-1 flex-shrink-0 ${dot}`} />
                      <div className="flex-1 min-w-0">
                        <div className="text-gray-800">{c.claim}</div>
                        {c.reasoning && (
                          <div className="text-gray-500 mt-0.5">{c.reasoning}</div>
                        )}
                        {c.source && (
                          <div className="text-gray-400 mt-0.5 truncate">
                            Source: {c.source.startsWith('http')
                              ? <a href={c.source} target="_blank" rel="noopener" className="hover:text-[#3ea8c8] underline">{c.source}</a>
                              : c.source}
                          </div>
                        )}
                        {fixable && (
                          <div className="mt-1.5 flex items-center gap-2">
                            <button
                              type="button"
                              onClick={() => previewFix(c, i)}
                              disabled={isFixing || wasApplied}
                              className={`text-[11px] font-medium px-2 py-0.5 rounded border disabled:opacity-50 ${
                                c.status === 'false'
                                  ? 'border-red-300 text-red-700 bg-white hover:bg-red-100'
                                  : 'border-yellow-300 text-yellow-800 bg-white hover:bg-yellow-100'
                              }`}
                            >
                              {wasApplied
                                ? '✓ Fix applied'
                                : isFixing
                                  ? 'Generating fix…'
                                  : 'Fix in article'}
                            </button>
                            {fixError && fixingIndex === null && fixPreview === null && (
                              <span className="text-[11px] text-red-700">{fixError}</span>
                            )}
                          </div>
                        )}
                      </div>
                      <span className="text-[10px] font-bold uppercase text-gray-500 flex-shrink-0">
                        {c.status === 'false' ? 'FALSE' : c.status}
                      </span>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      )}

      {!latestReport && !verifying && (
        <p className="mt-2 text-xs text-gray-500">
          Click <span className="font-medium">Run verification</span> to fact-check this article against public sources.
          {visibility === 'trash' && ' (Currently in trash — re-verifying will rescore but not auto-restore.)'}
        </p>
      )}

      {/* Fix-preview modal */}
      {fixPreview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onClick={closeModal}>
          <div
            className="bg-white rounded-lg shadow-xl max-w-3xl w-full max-h-[85vh] overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="px-5 py-4 border-b border-gray-200 flex items-center justify-between">
              <div>
                <h4 className="text-sm font-semibold text-gray-900">Review fix</h4>
                <p className="text-xs text-gray-500 mt-0.5">
                  Claim: <span className="italic">"{fixPreview.claim.claim.slice(0, 120)}{fixPreview.claim.claim.length > 120 ? '…' : ''}"</span>
                </p>
              </div>
              <button
                type="button"
                onClick={closeModal}
                disabled={applying}
                className="text-gray-400 hover:text-gray-600 text-xl leading-none"
                aria-label="Close"
              >
                ×
              </button>
            </div>

            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              {fixPreview.explanation && (
                <div className="text-xs text-gray-700 bg-blue-50 border border-blue-100 rounded p-2.5">
                  <span className="font-semibold text-blue-900">Explanation:</span> {fixPreview.explanation}
                </div>
              )}

              {!fixPreview.found && (
                <div className="text-xs text-amber-800 bg-amber-50 border border-amber-200 rounded p-2.5">
                  ⚠ The original text below was not found verbatim in the article. Applying the fix
                  will fail — the article may have been edited since fact-checking ran. Re-run verification
                  to refresh, or hand-edit the article directly.
                </div>
              )}

              <div>
                <div className="text-[11px] font-semibold uppercase text-red-700 mb-1">Original (will be removed)</div>
                <pre className="text-xs whitespace-pre-wrap break-words bg-red-50 border border-red-200 rounded p-2.5 text-gray-800">
                  {fixPreview.original_text}
                </pre>
              </div>

              <div>
                <div className="text-[11px] font-semibold uppercase text-green-700 mb-1">Replacement</div>
                <pre className="text-xs whitespace-pre-wrap break-words bg-green-50 border border-green-200 rounded p-2.5 text-gray-800">
                  {fixPreview.corrected_text || <span className="italic text-gray-500">(will be deleted — no replacement text)</span>}
                </pre>
              </div>

              {fixError && (
                <div className="text-xs text-red-700 bg-red-50 border border-red-200 rounded p-2.5">
                  {fixError}
                </div>
              )}
            </div>

            <div className="px-5 py-3 border-t border-gray-200 flex items-center justify-end gap-2">
              <button
                type="button"
                onClick={closeModal}
                disabled={applying}
                className="btn-outline text-xs disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={applyFix}
                disabled={applying || !fixPreview.found}
                className="btn-primary text-xs disabled:opacity-50"
              >
                {applying ? 'Applying…' : 'Apply fix to article'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
